replicaCount: 1

image:
  repository: ngodanghuy162/midterm
  pullPolicy: IfNotPresent
  tag: "backend_image"

service:
  type: NodePort
  port: 8080
  nodePort: 31000

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}
nodeSelector: {}
tolerations: []
affinity: []
